### ISSUE TITLE
Gradient shows when at bottom of page

### ISSUE THREAD

**Issue by Katchowski** [onkofonko/onkofonko.github.io#14]
## Issue in: public/theme/source.css

On servers with many channels and in DMs there is a permanent gradient that shows making it look like you have not reached the bottom of the page yet.

![image](https://github.com/onkofonko/onkofonko.github.io/assets/47070389/7b563eff-8d5f-4609-901c-97cbb4d0ff17)
![image](https://github.com/onkofonko/onkofonko.github.io/assets/47070389/1e85cd14-bc73-4384-acbe-75b64911b85c)

---

Ps: thank you for keeping this theme alive, I just found this after the dev deleted the og repo and I have been looking for a good theme replacement for a while.

**Comment by ockaj** [comment]
Hey there, the gradient is intentional, it was also present in the theme's official version.

**Comment by Katchowski** [comment]
ah, ok, sorry just one more question; is there a way that I can use this theme and still have the original discord profiles instead of the themes ones?

**Comment by ockaj** [comment]
It is possible, but it would require "deleting" a portion of the CSS code for the profiles, which is tedious.
